resolver: lts-20.17

packages:
- '.'

flags:
   serialise:
     newtime15: true

extra-deps:
- git: git@github.com:DataHaskell/dh-core.git
  commit: 02af0b351e0ee12b35df32741ad2363c863a652a
  subdir: datasets
- git: git@github.com:ejconlon/dahdit.git
  commit: f517f40fddcd02bec7f1306eb33bfcb66bfc3f1e
- data-sword-0.2.0.3
- flat-0.6
# - packman-0.5.0
