resolver: lts-20.17

packages:
- '.'

flags:
   serialise:
     newtime15: true

extra-deps:
- git: git@github.com:DataHaskell/dh-core.git
  commit: 02af0b351e0ee12b35df32741ad2363c863a652a
  subdir: datasets
- flat-0.6
# - packman-0.5.0
